#<189>2576: tankstelle_1-r: Nov 13 16:11:13.100: %HA_EM-5-LOG: ZTP-CDP-GigabitEthernet0/1/1: New neighbor detected: port2; GigabitEthernet0/1/1; tankstelle_1-port2-dev.ztp-domain; cisco WS-C3850-24U; Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.8.1a, RELEASE SOFTWARE (fc1)

messages:
  - error: EEM_CDP_NEIGHBOR
    tag: HA_EM-5-LOG
    values:
      eem_applet: (.*)
      ps_port: (\w+)
      interface: ([^;]*)
      device_fqdn: ([^;]*)
      device_model: ([^;]*)
      version: (.*)
    line: '{eem_applet}: New neighbor detected: {ps_port}; {interface}; {device_fqdn}; {device_model}; {version}'
    model: NO_MODEL
    mapping:
      static: {}
      variables:
        eem//cdp_neighbor//applet: eem_applet
        eem//cdp_neighbor//ps_port: ps_port
        eem//cdp_neighbor//interface: interface
        eem//cdp_neighbor//device_fqdn: device_fqdn
        eem//cdp_neighbor//model: device_model
        eem//cdp_neighbor//version: version